Repository primodiumxyz/reactive-tables, pull requests merged in 2024-06, with the labels that each got.

#11 Fix various issues
  __tests__/index.test.ts
  src/adapter/types.ts
  src/index.ts
  src/lib/external/mud/queries.ts
  src/queries/$query.ts
  src/queries/index.ts
  src/queries/types.ts
  src/queries/useQuery.ts
  src/tables/core/createContractTables.ts
  src/tables/core/createLocalTable.ts
  src/tables/core/createTable.ts
  src/tables/index.ts
  src/tables/methods/createTableKeyMethods.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/tables/types.ts
  src/utils.ts
Labels: kind/bug, kind/refactor, status/in-progress

#12 Fix utils
  src/lib/external/mud/indexer.ts
  src/lib/external/mud/queries.ts
  src/lib/external/mud/systems.ts
  src/lib/external/mud/tables.ts
  src/lib/external/mud/world.ts
  src/queries/$query.ts
  src/queries/query.ts
  src/queries/useQuery.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/utils.ts
Labels: kind/bug, status/testing

#13 Import from specific files
  src/adapter/createStorageAdapter.ts
  src/adapter/decodeProperties.ts
  src/adapter/types.ts
  src/lib/external/mud/entity.ts
  src/lib/external/mud/indexer.ts
  src/lib/external/mud/queries.ts
  src/lib/external/mud/schema.ts
  src/lib/external/mud/systems.ts
  src/lib/external/mud/tables.ts
  src/lib/external/mud/world.ts
  src/queries/$query.ts
  src/queries/query.ts
  src/queries/types.ts
  src/queries/useQuery.ts
  src/tables/core/createContractTables.ts
  src/tables/core/createLocalTable.ts
  src/tables/core/createTable.ts
  src/tables/methods/createTableKeyMethods.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/tables/types.ts
Labels: kind/bug, status/testing

#15 Add debug as dependency
  package.json
  pnpm-lock.yaml
Labels: kind/bug

#16 Build with typescript 5.5
  package.json
  pnpm-lock.yaml
Labels: kind/bug

#18 Clean up dependencies and optimize
  __tests__/utils/index.ts
  src/adapter/createStorageAdapter.ts
  src/adapter/decodeProperties.ts
  src/createWrapper.ts
  src/index.ts
  src/lib/definitions.ts
  src/lib/external/mud/entity.ts
  src/lib/external/mud/indexer.ts
  src/lib/external/mud/queries.ts
  src/lib/external/mud/schema.ts
  src/lib/external/mud/systems.ts
  src/lib/external/mud/tables.ts
  src/lib/external/mud/world.ts
  src/lib/index.ts
  src/queries/types.ts
  src/queries/useQuery.ts
  src/tables/core/createLocalTable.ts
  src/tables/core/createTable.ts
  src/tables/methods/createTableKeyMethods.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/tables/types.ts
  src/utils.ts
  tsconfig.json
  tsup.config.ts
Labels: kind/refactor, status/in-progress

#19 Minor improvements
  README.md
  __tests__/benchmarks/index.test.ts
  __tests__/benchmarks/package.json
  __tests__/index.test.ts
  __tests__/utils/networkConfig.ts
  __tests__/utils/sync/createSync.ts
  __tests__/utils/sync/handleSync.ts
  __tests__/utils/sync/types.ts
  package.json
  pnpm-lock.yaml
  src/adapter/encoder.ts
  src/adapter/index.ts
  src/createWrapper.ts
  src/index.ts
  src/lib/external/mud/queries.ts
  src/lib/external/mud/schema.ts
  src/lib/external/mud/systems.ts
  src/lib/external/mud/tables.ts
  src/queries/$query.ts
  src/queries/query.ts
  src/queries/types.ts
  src/queries/useQuery.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/tables/types.ts
  src/utils.ts
Labels: kind/feature, kind/refactor, status/draft

#23 Fix useQuery
  __tests__/index.test.tsx
  src/queries/useQuery.ts
  tsconfig.json
Labels: kind/bug

#24 Fix use() initial value
  src/tables/methods/createTableMethods.ts
Labels: kind/bug, status/testing

#21 Advanced queries and optimization
  __tests__/index.test.tsx
  __tests__/utils/actions.ts
  package.json
  pnpm-lock.yaml
  src/adapter/createStorageAdapter.ts
  src/adapter/decodeProperties.ts
  src/adapter/encoder.ts
  src/adapter/types.ts
  src/index.ts
  src/lib/external/mud/common.ts
  src/lib/external/mud/indexer.ts
  src/lib/external/mud/queries.ts
  src/lib/external/mud/schema.ts
  src/lib/external/mud/tables.ts
  src/lib/index.ts
  src/lib/persistence.ts
  src/queries/$query.ts
  src/queries/index.ts
  src/queries/query.ts
  src/queries/types.ts
  src/queries/useQuery.ts
  src/queries/utils.ts
  src/tables/core/createLocalTable.ts
  src/tables/core/createTable.ts
  src/tables/methods/createTableMethods.ts
  src/tables/methods/createTableWatcher.ts
  src/tables/types.ts
  src/utils.ts
  tsconfig.json
  tsconfig.prod.json
  tsup.config.ts
Labels: kind/feature, status/draft

#25 Improve schema handling
  .gitignore
  __tests__/type.test-d.ts
  package.json
  src/lib/external/mud/schema.ts
  src/tables/core/createLocalTable.ts
  src/tables/core/createTable.ts
  src/tables/methods/createTableKeyMethods.ts
  src/tables/types.ts
Labels: kind/bug
